# Generated by Django 4.1 on 2022-09-04 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 18, 21, 32, 798674, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
