# Generated by Django 4.1 on 2022-09-08 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_alter_timeline_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 15, 4, 13, 84977, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
