# Generated by Django 4.1 on 2022-09-09 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_alter_timeline_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 3, 18, 9, 227212, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
