# Generated by Django 4.1 on 2022-09-09 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_timeline_doc_timeline_pharma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='type',
            field=models.CharField(blank=True, default='user', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timeline_doc',
            name='type',
            field=models.CharField(blank=True, default='doc', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timeline_pharma',
            name='type',
            field=models.CharField(blank=True, default='pharma', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 14, 39, 27, 286047, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_doc',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 14, 39, 27, 286047, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_pharma',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 14, 39, 27, 286047, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
