# Generated by Django 4.1 on 2022-09-10 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_timeline_type_timeline_doc_type_timeline_pharma_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 4, 57, 37, 517669, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_doc',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 4, 57, 37, 517669, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_pharma',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 4, 57, 37, 517669, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
