# Generated by Django 4.1 on 2022-09-09 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0019_alter_timeline_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 18, 3, 4, 436391, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
