# Generated by Django 4.1 on 2022-09-09 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0022_alter_timeline_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 18, 27, 37, 997809, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
