# Generated by Django 4.1 on 2022-09-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_alter_timeline_datetime_alter_timeline_doc_datetime_and_more'),
        ('timeline', '0023_alter_timeline_datetime'),
    ]

    operations = [
    ]
