# Generated by Django 4.1 on 2022-09-12 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0024_merge_20220910_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 3, 59, 26, 727745, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_doc',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 3, 59, 26, 727745, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_pharma',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 3, 59, 26, 727745, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
