# Generated by Django 4.1 on 2022-09-11 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0024_alter_timeline_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 11, 10, 46, 381829, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
