# Generated by Django 4.1 on 2022-09-14 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0026_alter_timeline_datetime_alter_timeline_doc_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 3, 13, 9, 607724, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_doc',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 3, 13, 9, 607724, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_pharma',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 3, 13, 9, 607724, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
