# Generated by Django 4.1 on 2022-09-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_todolist_delete_todo_todoitem_todo_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='name_of_admin',
        ),
        migrations.AddField(
            model_name='todolist',
            name='name_of_admin',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
