# Generated by Django 4.1 on 2022-09-15 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 15, 46, 36, 321070, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
