<<<<<<< HEAD
# Generated by Django 4.1 on 2022-09-25 14:09
=======
# Generated by Django 4.1 on 2022-09-25 11:23
>>>>>>> 8ceb93665b11bcfdcf33787a2cc00baf01bb71d7

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
<<<<<<< HEAD
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 25, 14, 9, 29, 146029, tzinfo=datetime.timezone.utc), null=True),
=======
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 25, 11, 23, 19, 976095, tzinfo=datetime.timezone.utc), null=True),
>>>>>>> 8ceb93665b11bcfdcf33787a2cc00baf01bb71d7
        ),
    ]
